# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Oilogger
email: oilogger@roepcke.com
tagline: "Jim Roepcke's Oilers blog"
description: "Oilogger originally launched in the October, 2000, making it one of the first Oilers blogs in the world. This is version 2.0."

url: http://oilogger.com
baseurl: /

twitter_username: JimRoepckeOilrs

github_username:  oilogger
repository: oilogger/oilogger.github.io

# Build settings
markdown: kramdown
theme: minima

# Dependencies
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup

author:
  name:           'Jim Roepcke'
  url:            https://twitter.com/JimRoepckeOilrs

excerpt_separator: "<!--break-->"

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/oilogger/oilogger.github.io

# Gems
gems: [jekyll-paginate]
paginate: 5
paginate_path: "page:num"
